# Workflow is a customization of the Python starter
# workflow published in GitHub docs, 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
# The aim is to perform unit test using all operating
# systems, different Python versions, and different
# packaging versions.
#
# By: Robert Vogel

name: unit-tests

run-name: ${{ gethub.actor }} running unit-tests

# remember that YAML is a superset of JSON, therefore
# on.push.branches = [ main ]
# on.pull_request.branches = [ main ]
# is the equivalent to what is written below

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#, "3.8", "3.9", "3.10"]
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy matplotlib
      - name: Run unittest
        run: |
          python -m unittest




    
    


